name: 'Vault GCloud Action'
description: 'Authenticates to gcloud via Vault and then runs the provided script'
inputs:
    vaultUrl:
        description: 'Vault URL'
        required: true
    roleId:
        description: 'Role to authenticate to vault with'
        required: true
    secretId:
        description: 'Secret associated with role provided'
        required: true
    rolesetPath:
        description: 'Path to the GCP roleset in Vault'
        required: true
    script:
        description: 'script to run'
        required: true
    setBigQueryBiEngineReservation:
        description: 'Boolean value to allow setting the BigQuery BI Engine Reservation'
        required: false
        default: 'false'
    googleProjectId:
        description: 'Google Project ID'
        required: false
    location:
        description: 'Location for which the BI Engine reservation is to be set'
        required: false
        default: 'US'
    reservationBytesInGB:
        description: 'Set the Reservation Bytes in GB'
        required: false
    printScriptOutput:
        description: 'Whether to print stdout output from the script to the GitHub UI'
        required: false
        default: 'false'
runs:
    using: 'node12'
    main: 'dist/index.js'